Pin `ansible-core` to earlier than 2.16.3
cisagov/skeleton-ansible-role pull request #179
Opened 2024-03-10 16:24 UTC by jsf9k

## 🗣 Description ##

This pull request pins the `ansible-core` Python package's version to earlier than 2.16.3.

## 💭 Motivation and context ##

`ansible-core` 2.16.3 and later suffer from the bug discussed in ansible/ansible#82702, which breaks any symlinked files in `vars`, `tasks`, etc. for any Ansible role installed via `ansible-galaxy`.  This results in [AMI build failures](https://github.com/cisagov/openvpn-packer/actions/runs/8205777362/job/22446435052) as seen in cisagov/openvpn-packer#101.

## 🧪 Testing ##

All automated testing passes in this pull request, and in cisagov/openvpn-packer#101 the build [gets further than it did upon addition of these changes](https://github.com/cisagov/openvpn-packer/actions/runs/8208824296/job/22453124370?pr=101).  (The build continues to fail, but for a different reason.)

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All new and existing tests pass.

2024-03-10 17:39 UTC, dav3r approved these changes
👍 with one tiny change requested

2024-03-10 17:39 UTC, dav3r commented on requirements-test.txt
> +# See also cisagov/skeleton-packer##312.
Remove bonus octothorpe:
```suggestion
# See also cisagov/skeleton-packer#312.
```

2024-03-10 20:17 UTC, mcdonnnj approved these changes
LGTM ✔

2024-03-11 12:53 UTC, dv4harr10 approved these changes

2024-03-19 19:13 UTC, mcdonnnj requested changes
@jsf9k Sorry this only came to me yesterday but I would like to add a dependabot ignore directive for this newly explicit dependency here:
https://github.com/cisagov/skeleton-ansible-role/blob/166674527f743553dfae7b193a89b18f6460ef45/.github/dependabot.yml#L27-L30

I don't know if it's strictly necessary but I would like to avoid a storm of dependabot PRs around this dependency downstream.

2024-03-19 19:20 UTC, jsf9k commented
> @jsf9k Sorry this only came to me yesterday but I would like to add a dependabot ignore directive for this newly explicit dependency here:
> 
> https://github.com/cisagov/skeleton-ansible-role/blob/166674527f743553dfae7b193a89b18f6460ef45/.github/dependabot.yml#L27-L30
> 
> I don't know if it's strictly necessary but I would like to avoid a storm of dependabot PRs around this dependency downstream.

Please see commit 13219ff.

2024-03-19 19:24 UTC, mcdonnnj approved these changes
_Approval intensifies._ :godmode:

2024-03-19 19:34 UTC, jsf9k commented
See also cisagov/skeleton-packer#315.

2024-03-27 08:29 UTC, merged